[server_internal]
host = "0.0.0.0"
port = 3100

[server_external]
host = "0.0.0.0"
port = 3101

[redis]
url = "redis://localhost:6379/0"

[application]
short_url_base = "http://localhost:3101"
long_url_base = "didcomm://example.com"
