[server]
host = "0.0.0.0"
port = 3100
enable_tls = false

[redis]
url = "redis://localhost:6379/0"

[application]
short_url_base = "http://sh.local.absa.africa"
long_url_base = "didcomm://example.com"
