name: Check version

outputs:
  publish-version:
    description: Version of the published artifacts
    value: ${{ steps.check-version.outputs.publish-version }}
  is-release:
    description: Whether publish a release or not
    value: ${{ steps.check-version.outputs.is-release }}

env:
  DOCKER_BUILDKIT: 1

runs:
  using: "composite"
  steps:
    - name: Check for desired version of published artifacts
      id: check-version
      run: |
        if [[ -z "$GITHUB_HEAD_REF" ]]; then # is set only if pipeline run is triggered as pull request
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Setting BRANCH_NAME=$BRANCH_NAME because this pipeline is run as push"
        else
          BRANCH_NAME=$GITHUB_HEAD_REF
          echo "Setting BRANCH_NAME=$BRANCH_NAME because this pipeline is run as Pull Request"
        fi

        BRANCH_NAME=`echo $BRANCH_NAME | sed "s/[^[:alnum:]-]//g" | tr '[:upper:]' '[:lower:]'` # lowercase, only alphanumeric and dash

        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "PR Labels: ${{ toJson(github.event.pull_request.labels.*.name) }}"

          REPO_HEAD="${{ github.event.pull_request.head.repo.full_name }}" # source repository
          REPO_BASE="${{ github.event.pull_request.head.base.full_name }}" # target repository
          echo "This is pull request from $REPO_HEAD to $REPO_BASE"

          if [[ "$REPO_HEAD" == "${{ github.repository }}" ]]; then
            echo "This CI run is PR from non-forked repository."
            IS_FORK="false";
          else
            echo "This is fork."
            IS_FORK="true";
          fi;
        else
          echo "Not PR so this is not fork."
          IS_FORK="false";
        fi;

        REPO_VERSION_MOST_RECENT=$(git describe --tags --always --abbrev=0)
        REPO_VERSION_DESIRED=$(cargo pkgid --manifest-path Cargo.toml | cut -d# -f2 | cut -d: -f2)
        echo "Highest released version was: $REPO_VERSION_MOST_RECENT, desired version (specified in Cargo.toml) is $REPO_VERSION_DESIRED"

        IS_RELEASE="false"

        if [[ "$IS_FORK" == "false" ]]; then
          if [[ "${{ github.event_name }}" == "push" ]]; then
            if [[ "$BRANCH_NAME" == "main" && "$REPO_VERSION_DESIRED" != "$REPO_VERSION_MOST_RECENT" ]]; then
              PUBLISH_VERSION="$REPO_VERSION_DESIRED"
              IS_RELEASE="true"
              echo "This is push to main, and version was bumped from $REPO_VERSION_MOST_RECENT to $REPO_VERSION_DESIRED. Will publish a release of $REPO_VERSION_DESIRED."
            fi;
          fi;

          if [[ -z "$PUBLISH_VERSION" ]]; then
            PUBLISH_VERSION="$REPO_VERSION_MOST_RECENT-$BRANCH_NAME-${{ github.run_number }}"
          fi;

          echo "CI will publish artifacts at version: $PUBLISH_VERSION"
        else
          echo "This PR is from fork, nothing will be published because the CI wouldn't be able to access repo secrets to perform publish."
          PUBLISH_VERSION=""
        fi;

        echo "::set-output name=publish-version::$PUBLISH_VERSION"
        echo "::set-output name=is-release::$IS_RELEASE"
      shell: bash
